# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03fcaa4c6110dff4bb62ebba6008744ad9c89e97580334319738a1ed7cfbdd498f4ce3e2e92b33dd4716a45c73dd459d3e6b0a8696008bccb95acc651130e98b

test:
  secret_key_base: 6e12bc99d4afd9bfb0f7e92aa11b96a51f00de629445b6b56ebd5e3a623cefafd757cc0c6be7b688c7059166652b7c20c898a4df9ba80d7d368eccf284c3bb65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
